resolver: lts-6.31
packages:
- '.'
- location:
    git: https://github.com/zinfra/amazonka-limited
    commit: e81b14a0bc236a956adceec7090f16b996d83ad3
  extra-dep: true
extra-deps:
- aeson-1.1.1.0
- base-compat-0.9.3
- base-orphans-0.6
- ede-0.2.8.7
- either-4.3.4.1
- exceptions-0.6.1
- mmorph-1.0.9
- prelude-prime-0.1
- querystring-pickle-0.2.0
- tagged-0.8.5
- transformers-compat-0.5.1.4
- trifecta-1.6.2.1
allow-newer: true
